Ansible galaxy requires these packages
geerlingguy/docker-centos6-ansible pull request #6
Opened 2018-08-20 19:19 UTC by bdellegrazie

- Ansible galaxy now uses SNI and breaks without these packages

2018-08-20 20:23 UTC, geerlingguy requested changes

2018-08-20 20:23 UTC, geerlingguy commented on Dockerfile
> +      python-pyasn1
This line still needs a `\` at the end.

2018-08-20 21:35 UTC, bdellegrazie commented
@geerlingguy fixed - sorry, missed that.

2018-08-21 14:53 UTC, geerlingguy approved these changes

2018-08-21 14:54 UTC, merged